// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


//Setup
const UPPER_LIMIT_4_000_000 =4000000;
let fibSeq = [];
fibSeq.push(1);
fibSeq.push(1);
let termNumber=1;

while( (fibSeq[termNumber]+fibSeq[termNumber-1]) < UPPER_LIMIT_4_000_000 ){
  fibSeq.push( fibSeq[termNumber] + fibSeq[termNumber-1] )
  termNumber = termNumber + 1;
}
console.log(fibSeq);


let evenSum = fibSeq.reduce(function(sum, currentTerm){
  // console.log('BeforeTest sum: ', sum)
  if(currentTerm %2 ===0){
    sum = sum + currentTerm;
    // console.log('in test', currentTerm)
  }
  // console.log('After test sum: ', sum)
  return sum;
}, 0);

console.log(`The Sum of all even terms is: ${evenSum}`);
